# -*- coding: utf-8 -*-
"""DAV ASSIGNMENT -1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G2SXDvAsMrd8QaUGr9n3LJst-5NM7vKD

1.Data Science Mini Project: Predicting Student Marks from Study Hours using Pandas, Matplotlib, Linear Regression, and R² Score.
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# Sample dataset of 10 students
data = {
    'Study_Hours': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Marks': [35, 40, 50, 55, 60, 68, 75, 80, 88, 95]
}

# Create DataFrame
df = pd.DataFrame(data)

print("Dataset:")
print(df)

# Independent variable (X) and Dependent variable (y)
X = df[['Study_Hours']]
y = df['Marks']

# Create and train Linear Regression model
model = LinearRegression()
model.fit(X, y)

# Predict marks
y_pred = model.predict(X)

# Calculate R² Score
r2 = r2_score(y, y_pred)

print("\nModel Performance")
print("R² Score:", round(r2, 4))
print("Slope (Coefficient):", model.coef_[0])
print("Intercept:", model.intercept_)

# Predict marks for a student studying 7.5 hours
hours = [[7.5]]
predicted_marks = model.predict(hours)

print("\nPredicted Marks for 7.5 Study Hours:",
      round(predicted_marks[0], 2))

# Visualization
plt.scatter(X, y, color='blue', label='Actual Data')
plt.plot(X, y_pred, color='red', linewidth=2,
         label='Regression Line')

plt.title('Study Hours vs Marks')
plt.xlabel('Study Hours')
plt.ylabel('Marks')
plt.legend()
plt.grid(True)

plt.show()

"""2.Sales Prediction : independent variable is Advertising Budget (in ₹1000s) and the dependent variable is Sales (in Units)"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# Sample dataset of 10 months
data = {
    'Advertising_Budget': [10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
    'Sales': [120, 150, 180, 210, 240, 270, 300, 330, 360, 390]
}

# Create DataFrame
df = pd.DataFrame(data)

print("Dataset:")
print(df)

# Dataset Information
print("\nDataset Information:")
print(df.info())

# Check Missing Values
print("\nMissing Values:")
print(df.isnull().sum())

# Statistical Summary
print("\nStatistical Summary:")
print(df.describe())

# Independent variable (X) and Dependent variable (y)
X = df[['Advertising_Budget']]
y = df['Sales']

# Create and train Linear Regression model
model = LinearRegression()
model.fit(X, y)

# Predict Sales
y_pred = model.predict(X)

# Calculate R² Score
r2 = r2_score(y, y_pred)

print("\nModel Performance")
print("R² Score:", round(r2, 4))
print("Slope (Coefficient):", model.coef_[0])
print("Intercept:", model.intercept_)

# Predict sales for an advertising budget of 37.5
budget = [[37.5]]
predicted_sales = model.predict(budget)

print("\nPredicted Sales for Advertising Budget of 37.5:")
print(round(predicted_sales[0], 2))

# Visualization
plt.scatter(X, y, color='blue', label='Actual Data')
plt.plot(X, y_pred, color='red', linewidth=2, label='Regression Line')

plt.title('Advertising Budget vs Sales')
plt.xlabel('Advertising Budget (₹1000s)')
plt.ylabel('Sales (Units)')
plt.legend()
plt.grid(True)

plt.show()

"""3.Banking Mini Project : The model predicts the Loan Amount Approved based on the Customer's Annual Income."""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# Sample dataset of 10 customers
data = {
    'Annual_Income': [2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0],
    'Loan_Amount': [1.5, 1.8, 2.1, 2.5, 2.9, 3.3, 3.7, 4.1, 4.5, 4.9]
}

# Create DataFrame
df = pd.DataFrame(data)

print("Dataset:")
print(df)

# Dataset Information
print("\nDataset Information:")
print(df.info())

# Check Missing Values
print("\nMissing Values:")
print(df.isnull().sum())

# Statistical Summary
print("\nStatistical Summary:")
print(df.describe())

# Independent variable (X) and Dependent variable (y)
X = df[['Annual_Income']]
y = df['Loan_Amount']

# Create and train Linear Regression model
model = LinearRegression()
model.fit(X, y)

# Predict Loan Amount
y_pred = model.predict(X)

# Calculate R² Score
r2 = r2_score(y, y_pred)

print("\nModel Performance")
print("R² Score:", round(r2, 4))
print("Slope (Coefficient):", model.coef_[0])
print("Intercept:", model.intercept_)

# Predict loan amount for a customer with annual income of 5.8 lakhs
income = [[5.8]]
predicted_loan = model.predict(income)

print("\nPredicted Loan Amount for Annual Income of 5.8 Lakhs:")
print(round(predicted_loan[0], 2), "Lakhs")

# Visualization
plt.scatter(X, y, color='blue', label='Actual Data')
plt.plot(X, y_pred, color='red', linewidth=2,
         label='Regression Line')

plt.title('Annual Income vs Loan Amount')
plt.xlabel('Annual Income (Lakhs)')
plt.ylabel('Loan Amount (Lakhs)')
plt.legend()
plt.grid(True)

plt.show()